/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UsersLazyImport = createFileRoute('/users')()
const MyprofileLazyImport = createFileRoute('/myprofile')()
const LoginLazyImport = createFileRoute('/login')()
const AcquisitionsLazyImport = createFileRoute('/acquisitions')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UsersLazyRoute = UsersLazyImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/users.lazy').then((d) => d.Route))

const MyprofileLazyRoute = MyprofileLazyImport.update({
  id: '/myprofile',
  path: '/myprofile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/myprofile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AcquisitionsLazyRoute = AcquisitionsLazyImport.update({
  id: '/acquisitions',
  path: '/acquisitions',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/acquisitions.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/acquisitions': {
      id: '/acquisitions'
      path: '/acquisitions'
      fullPath: '/acquisitions'
      preLoaderRoute: typeof AcquisitionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/myprofile': {
      id: '/myprofile'
      path: '/myprofile'
      fullPath: '/myprofile'
      preLoaderRoute: typeof MyprofileLazyImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/acquisitions': typeof AcquisitionsLazyRoute
  '/login': typeof LoginLazyRoute
  '/myprofile': typeof MyprofileLazyRoute
  '/users': typeof UsersLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/acquisitions': typeof AcquisitionsLazyRoute
  '/login': typeof LoginLazyRoute
  '/myprofile': typeof MyprofileLazyRoute
  '/users': typeof UsersLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/acquisitions': typeof AcquisitionsLazyRoute
  '/login': typeof LoginLazyRoute
  '/myprofile': typeof MyprofileLazyRoute
  '/users': typeof UsersLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acquisitions' | '/login' | '/myprofile' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acquisitions' | '/login' | '/myprofile' | '/users'
  id: '__root__' | '/' | '/acquisitions' | '/login' | '/myprofile' | '/users'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AcquisitionsLazyRoute: typeof AcquisitionsLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MyprofileLazyRoute: typeof MyprofileLazyRoute
  UsersLazyRoute: typeof UsersLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AcquisitionsLazyRoute: AcquisitionsLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MyprofileLazyRoute: MyprofileLazyRoute,
  UsersLazyRoute: UsersLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/acquisitions",
        "/login",
        "/myprofile",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/acquisitions": {
      "filePath": "acquisitions.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/myprofile": {
      "filePath": "myprofile.lazy.tsx"
    },
    "/users": {
      "filePath": "users.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
